Add files via upload
Xuanwen1101/HospitalProject-Group3 pull request #8
Opened 2022-07-21 01:45 UTC by AvidMaker12

2022-07-24 04:37 UTC, deisy25 approved these changes

2022-07-24 18:31 UTC, Xuanwen1101 requested changes
Please git pull from the master branch before creating the PR for merging.

2022-07-24 23:48 UTC, deisy25 approved these changes

2022-07-24 23:48 UTC, deisy25 approved these changes

2022-07-26 15:52 UTC, Xuanwen1101 requested changes
Your [HospitalProject-Group3.csproj] is missing some new controllers and views from last week.

2022-07-28 04:38 UTC, closed without merging